### ISSUE TITLE
RuntimeError: un-supported index_bits:10

### ISSUE THREAD

**Issue by Excuses123** [microsoft/VPTQ#71]
Hello, I've encountered this issue while using the model you provided for inference. What might be causing it?

```CUDA_VISIBLE_DEVICES=1 python -m vptq --model=VPTQ-community/Qwen2.5-72B-Instruct-v8-k1024-512-woft --chat
Namespace(model='VPTQ-community/Qwen2.5-72B-Instruct-v8-k1024-512-woft', tokenizer='', prompt='once upon a time, there ', chat=True, chat_system_prompt='you are a math teacher.')
Replacing linear layers...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1127/1127 [00:00<00:00, 1128.38it/s]
Fetching 17 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 81863.57it/s]
Some parameters are on the meta device because they were offloaded to the cpu.                                                                                         
============================chat with the model============================
Press 'exit' to quit
You: hello
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.10/site-packages/vptq/__main__.py", line 8, in <module>
    main()
  File "/root/anaconda3/lib/python3.10/site-packages/vptq/app_utils.py", line 137, in main
    chat_loop(model, tokenizer, args)
  File "/root/anaconda3/lib/python3.10/site-packages/vptq/app_utils.py", line 65, in chat_loop
    generated_ids = model.generate(model_inputs,
  File "/root/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1167, in forward
    outputs = self.model(
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 976, in forward
    layer_outputs = decoder_layer(
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 702, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 580, in forward
    query_states = self.q_proj(hidden_states)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/vptq/layers/vqlinear.py", line 649, in forward
    qweight = self.fast_dequant()
  File "/root/anaconda3/lib/python3.10/site-packages/vptq/layers/vqlinear.py", line 485, in fast_dequant
    output = ops.dequant(
RuntimeError: un-supported index_bits:10```

**Comment by YangWang92** [comment]
The issue might be at this line: https://github.com/microsoft/VPTQ/blob/main/csrc/dequant_impl_packed.cu#L366. To reduce compilation time, we removed support for 10-bit bitwidth. You can add it back and recompile to solve the problem.
```cpp
    case 10:                                                                        \
      callDequantWithOutliers_dtype(10, BASEGROUP, OUT_OUF_INF, ResidualBits);      \
      break;  
```

**Comment by YangWang92** [comment]
or you can use other models/settings from community release under the similar performance & accuracy.

**Comment by Excuses123** [comment]
@YangWang92 Okay, I've got it, thank you for your answer.
